//findAll
GET http://localhost:3003/products
Content-Type: application/json
###
//ProductList
POST http://localhost:3003/orders
Content-Type: application/json

{ 
  "name": "teste",
  "dlr_date": "2022/11/01",
  "products_id": [16, 19],
  "product_qty": [1, 1],
  "total_price": 1
}

